AWSTemplateFormatVersion: 2010-09-09
Description: Sample template for uninstall and clean up of Linux Falcon sensor daemon service on your ECS cluster
Parameters:
  ECSClusterName:
    Type: String
    Description: ECS cluster name where your Linux Falcon sensor daemon service has been deployed
  FalconImagePath:
    Type: String
    Description: The ECR image path including tag value for the Linux Falcon sensor container image

  EnableLogging:
    Type: String
    Description: Boolean string to enable logging for the Falcon ECS service.
    Default: false
    AllowedValues:
      - true
      - false
  ECSTaskRoleArn:
    Type: String
    Description: Task role name to exec in to the Falcon container. Only required if logging is enabled.
    Default: ""
  CapacityProviderName:
    Type: String
    Default: ""
    Description: Name of the ECS capacity provider to constrain daemon scheduling. Leave empty to schedule on all instances regardless of capacity provider.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Mandatory Fields
        Parameters:
          - ECSClusterName
          - FalconImagePath

Conditions:
  IsLoggingEnabled: !Equals [!Ref EnableLogging, "true"]
  IsTaskRoleRequired: !Condition IsLoggingEnabled
  HasCapacityProviderName: !Not [!Equals [!Ref CapacityProviderName, ""]]

Resources:
  FalconECSTaskDefinition:
    Type: AWS::ECS::DaemonTaskDefinition
    Properties:
      PidMode: shared
      TaskRoleArn: !If
        - IsTaskRoleRequired
        - !Ref ECSTaskRoleArn
        - !Ref AWS::NoValue
      ContainerDefinitions:
        - Name: cleanup-opt-crowdstrike
          MemoryReservation: 128
          Image: !Ref FalconImagePath
          EntryPoint:
            - "/bin/bash"
          Command:
            - '-c'
            - 'echo "Running /opt/CrowdStrike/falcon-daemonset-init -u"; /opt/CrowdStrike/falcon-daemonset-init -u'
          Essential: false
          Privileged: true
          ReadonlyRootFilesystem: false
          User: 0
          LogConfiguration: !If
            - IsLoggingEnabled
            - LogDriver: awslogs
              Options:
                awslogs-group: !Sub "/aws/ecs/${ECSClusterName}/crowdstrike/falcon-daemon-service"
                awslogs-region: !Ref AWS::Region
                awslogs-stream-prefix: "falcon-node-init"
            - !Ref AWS::NoValue
        - Name: cleanup-sleep
          Image: !Ref FalconImagePath
          EntryPoint:
            - "/bin/bash"
          Command:
            - '-c'
            - 'sleep 300'
          Essential: true
          DependsOn:
            - ContainerName: cleanup-opt-crowdstrike
              Condition: COMPLETE
          MemoryReservation: 128
          Privileged: false
          ReadonlyRootFilesystem: true
          LogConfiguration: !If
            - IsLoggingEnabled
            - LogDriver: awslogs
              Options:
                awslogs-group: !Sub "/aws/ecs/${ECSClusterName}/crowdstrike/falcon-daemon-service"
                awslogs-region: !Ref AWS::Region
                awslogs-stream-prefix: "falcon-node-sensor"
            - !Ref AWS::NoValue

  FalconECSCleanupDaemon:
    Type: AWS::ECS::Daemon
    Properties:
      ClusterArn: !Sub "arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${ECSClusterName}"
      DaemonName: crowdstrike-falcon-cleanup-daemon
      CapacityProviderArns: !If
        - HasCapacityProviderName
        - - !Sub "arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:capacity-provider/${CapacityProviderName}"
        - !Ref AWS::NoValue
      EnableECSManagedTags: true
      DaemonTaskDefinitionArn: !Ref FalconECSTaskDefinition

  FalconECSServiceLogGroup:
    Type: AWS::Logs::LogGroup
    Condition: IsLoggingEnabled
    Properties:
      LogGroupName: !Sub "/aws/ecs/${ECSClusterName}/crowdstrike/falcon-daemon-service"